# pnpm workspace configuration
packages:
  - "angular-shell"
  - "Scramble-Words"
  - "life-goals"
  - "quiz-game"
  - "life-milestone-race"
  - "retirement-readiness-journey"
  - "financial-match-arena"
  - "retirement-sudoku"
  - "financial-tetris"
